### ISSUE TITLE
Not working in Notepad++ v8.4.6 2022-09-29

### ISSUE THREAD

**Issue by ungribbled** [Dook1/Bookmarks-Dook#18]
BookmarksDook was working great for me up to and including Notepad++ v8.4.5.
No longer seems to be working in Notepad++ v8.4.6 (2022-09-29).
Bookmark image shows as normal but nothing shows in bookmark panel no matter what I do - so ther's nothing to click on.
I've even tried shutting Notepad++ and then deleting BookmarksDook.ini, then restarting in both 32-bit and 64-bit.

**Comment by Iton-Horn** [comment]
Same problem.
Last version of Notepad++ where the BookmarksDook works is 8.4.5.
See also here
[https://community.notepad-plus-plus.org/post/80174](url)

**Comment by Dook1** [comment]
I'll look into it next week.

**Comment by Dook1** [comment]
In version 8.4.6 they changed the bookmark's marker number for some reason. Before it was 24 and now it is 20. Let them change it back. I will not support an individual marker for each version.

**Comment by HanzieV** [comment]
Hi,  I realy love BookmarksDook, it has already saved me tons of time.  The fact that is has stopped working is realy a big problem for me.  My company does not allow me to downgrade my NP++ so I need another solution.  I suppose the people at NP++ had a good reason to change the marker and I don't think they will be willing to change it back again just for me so I'm realy hoping for another solution.

**Comment by Dook1** [comment]
Install 8.4.5 in another folder.

**Comment by NeilS-Wpg** [comment]
Hi Mr. Dook.

FYI, there was subsequent discussion (same thread) about that marker id, and Don Ho stated that a new API that makes the id fetchable rather than hard coded will be available in the next release.

Also FYI, I am an admiring daily user of the bookmarks panel as well; I enjoy the persistence across restarts.

Also FYI (and sorry if it's old news) I noticed plugin shortcuts Ctrl+1 to Ctrl+5 don't function as bookmark shortcuts; those key combos conflict with their (at some point "new") native use, which is to hop through instances of styled text (menu item "Jump down" under Search). Observed in npp v 8.1.9. I never used those key combos myself.

**Comment by Dook1** [comment]
Ok, waiting for the next release. Although this API should have been available in the release in which the bookmarker number was changed.
As for the keys, they change in the NPP settings.

**Comment by Dook1** [comment]
fixed in 3.0.0
https://github.com/Dook1/Bookmarks-Dook/releases/tag/3.0

**Comment by ungribbled** [comment]
Thanks Dook1. Really appreciated!

**Comment by HanzieV** [comment]
Great, thanks a lot !
